Update setuptools etc after installing conda dependencies.
CircleCI tests recently started failing, probably due to
something in the conda dependency stack downgrading setuptools?
Got this in the mamba install logs:

Downgrade:
──────────────────────────────────────────────────────────────────────────────────────────────

  - setuptools                   65.5.1  pyhd8ed1ab_0         conda-forge
  + setuptools                   59.8.0  py37h89c1867_1       conda-forge/linux-64       1MB

And then a failure later which suggests the old setuptools is
to blame::

ModuleNotFoundError: No module named 'setuptools.command.build'