Try a minimal RTD configuration
In the absense of a configuration file, seems
RTD defaults to the very old Sphinx 1.8.5.
This recently broke with the release of
docutils-0.18, giving us this exception:

Exception occurred:
  File /home/docs/checkouts/readthedocs.org/user_builds/thapbi-pict/envs/latest/lib/python3.7/site-packages/sphinx/builders/latex/__init__.py, line 201, in write
    if toctrees[0].get('maxdepth') > 0:
TypeError: 'generator' object is not subscriptable

We can either specify specific versions including
docutils-0.17.1, or try the latest release...